'use client';

import { useMemo, useState } from 'react';

type FormState = {
  name: string;
  age: string;
  gender: string;
  pregnant: string;
  country: string;
  duration: string;
  symptoms: string[];
  redFlags: string[];
  notes: string;
};

type TriageResult = {
  level: string;
  destination: string;
  urgency: string;
  advice: string;
  summary: string;
  routeType: 'emergency' | 'doctor' | 'pharmacist' | 'selfcare';
};

const initialForm: FormState = {
  name: '',
  age: '',
  gender: '',
  pregnant: 'no',
  country: 'South Africa',
  duration: '',
  symptoms: [],
  redFlags: [],
  notes: '',
};

const symptoms = [
  'Backache',
  'Bites',
  'Cold and Flu',
  'Dental Pain',
  'Earache',
  'Eye Infection',
  'Hayfever',
  'Menstrual Pain',
  'Palpitations',
  'Poisoning',
  'Rashes',
  'Red Eyes',
  'Urinary Tract Infection',
].sort();

const redFlags = [
  'Chest pain',
  'Difficulty breathing',
  'Severe bleeding',
  'Confusion',
  'Loss of consciousness',
  'Severe dehydration',
  'Stroke symptoms',
];

function decideTriage(form: FormState): TriageResult {
  if (
    form.redFlags.length > 0 ||
    form.symptoms.includes('Poisoning') ||
    form.symptoms.includes('Palpitations')
  ) {
    return {
      level: 'Emergency',
      destination: 'Emergency care',
      urgency: 'Immediate',
      advice:
        'Seek urgent emergency medical attention immediately. In South Africa, call Netcare 911 on 082 911 or local emergency services.',
      summary:
        'Red flag or high-risk symptoms were selected and require emergency escalation.',
      routeType: 'emergency',
    };
  }

  if (
    form.symptoms.includes('Dental Pain') ||
    form.symptoms.includes('Earache') ||
    form.symptoms.includes('Eye Infection') ||
    form.symptoms.includes('Urinary Tract Infection') ||
    form.duration === 'More than 3 days' ||
    form.duration === 'Sudden or worsening' ||
    form.pregnant === 'yes' ||
    form.pregnant === 'unsure'
  ) {
    return {
      level: 'Doctor / Prescribing Pharmacist',
      destination: 'GP or Prescribing Pharmacist',
      urgency: 'Today or within 24 hours',
      advice:
        'A clinical assessment is recommended. Refer to a GP, doctor in pharmacy, or prescribing pharmacist.',
      summary:
        'The symptoms may require examination, prescribing, or further clinical assessment.',
      routeType: 'doctor',
    };
  }

  return {
    level: 'Pharmacist care',
    destination: 'Pharmacy care',
    urgency: 'Routine',
    advice:
      'Pharmacist-led care, OTC advice, monitoring, and safety-net counselling are appropriate.',
    summary:
      'No urgent red flags were selected and the symptoms appear suitable for pharmacy-led care.',
    routeType: 'pharmacist',
  };
}

export default function Page() {
  const [form, setForm] = useState<FormState>(initialForm);
  const [result, setResult] = useState<TriageResult | null>(null);

  const selectedSymptoms = useMemo(() => form.symptoms.join(', '), [form.symptoms]);

  function update<K extends keyof FormState>(key: K, value: FormState[K]) {
    setForm((prev) => ({ ...prev, [key]: value }));
  }

  function toggleSymptom(symptom: string) {
    setForm((prev) => ({
      ...prev,
      symptoms: prev.symptoms.includes(symptom)
        ? prev.symptoms.filter((s) => s !== symptom)
        : [...prev.symptoms, symptom],
    }));
  }

  function toggleRedFlag(flag: string) {
    setForm((prev) => ({
      ...prev,
      redFlags: prev.redFlags.includes(flag)
        ? prev.redFlags.filter((f) => f !== flag)
        : [...prev.redFlags, flag],
    }));
  }

  function submitTriage() {
    setResult(decideTriage(form));
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }

  function newTriage() {
    setForm(initialForm);
    setResult(null);
  }

  const carelinkUrl =
    form.country === 'South Africa'
      ? 'https://carelink.digital'
      : 'https://cpnbs.carelink.digital/home';

  const pharmacistRouteUrl =
    form.country === 'South Africa'
      ? 'https://carelink.digital'
      : 'https://nhs.carelink.digital';

  function reportText() {
    return `SYMPTOMAI TRIAGE REPORT

Patient: ${form.name || 'Not provided'}
Age: ${form.age || 'Not provided'}
Gender: ${form.gender || 'Not provided'}
Pregnant: ${form.gender === 'female' ? form.pregnant : 'Not applicable'}
Country: ${form.country}

Symptoms: ${selectedSymptoms || 'None selected'}
Duration: ${form.duration || 'Not selected'}
Red flags: ${form.redFlags.length ? form.redFlags.join(', ') : 'None selected'}
Notes: ${form.notes || 'None'}

Outcome: ${result?.level}
Destination: ${result?.destination}
Urgency: ${result?.urgency}
Advice: ${result?.advice}
Summary: ${result?.summary}

Clinical references:
NICE Clinical Knowledge Summaries, South African Primary Care/STG/EML principles, pharmacist referral guidance, WHO emergency escalation principles.

Generated by SymptomAI.`;
  }

  function downloadPDF() {
    const html = `
      <html>
        <head>
          <title>SymptomAI Triage Report</title>
          <style>
            body { font-family: Arial; padding: 40px; color: #071b3d; }
            h1 { font-size: 32px; }
            pre { white-space: pre-wrap; font-size: 15px; line-height: 1.5; }
          </style>
        </head>
        <body>
          <h1>SymptomAI Triage Report</h1>
          <pre>${reportText()}</pre>
        </body>
      </html>
    `;
    const win = window.open('', '_blank');
    if (!win) return;
    win.document.write(html);
    win.document.close();
    win.print();
  }

  function installApp() {
    alert('To install SymptomAI, open the browser menu and select “Add to Home screen”.');
  }

  const whatsappLink = `https://wa.me/?text=${encodeURIComponent(reportText())}`;
  const emailLink = `mailto:?subject=SymptomAI Triage Report&body=${encodeURIComponent(reportText())}`;

  return (
    <>
      <style jsx global>{`
        * { box-sizing: border-box; }
        html, body {
          margin: 0;
          background: linear-gradient(135deg, #eefafa 0%, #f7fbff 100%);
          color: #071b3d;
          font-family: Arial, Helvetica, sans-serif;
        }
        .page { max-width: 880px; margin: 0 auto; padding: 30px 18px 80px; }
        .brand { display: flex; align-items: center; gap: 14px; margin-bottom: 28px; }
        .brand-icon {
          width: 72px; height: 72px; border-radius: 22px;
          background: #071b3d; color: #1dd5c5;
          display: flex; align-items: center; justify-content: center;
          font-size: 56px; font-weight: 900;
        }
        .brand-title { font-size: 52px; font-weight: 900; line-height: .95; }
        .brand-subtitle { color: #667785; font-size: 18px; font-weight: 800; margin-top: 6px; }
        .card {
          background: rgba(255,255,255,.92);
          border-radius: 34px;
          padding: 34px;
          margin-bottom: 24px;
          box-shadow: 0 18px 55px rgba(7,27,61,.09);
          border: 1px solid rgba(7,27,61,.06);
        }
        .hero h1, .result h1 {
          font-size: 54px; line-height: .98; margin: 0 0 20px;
          font-weight: 900; letter-spacing: -1.5px;
        }
        h2 { font-size: 34px; margin: 0 0 18px; font-weight: 900; }
        p { color: #647480; font-size: 20px; line-height: 1.5; }
        .alert {
          background: #fff3f3; border: 2px solid #ffd1d1; color: #8a1f1f;
          border-radius: 22px; padding: 18px; margin-bottom: 22px; font-weight: 800;
        }
        .chat {
          background: #f4fbfb; border: 1px solid #dceeee;
          border-radius: 24px; padding: 18px; margin-bottom: 20px;
          color: #61727f; font-size: 18px; line-height: 1.5;
        }
        .chat strong { color: #071b3d; display: block; margin-bottom: 5px; }
        .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
        label { display: block; font-size: 17px; font-weight: 900; margin-bottom: 8px; }
        input, select, textarea {
          width: 100%; border: 2px solid #dfe9ea; border-radius: 18px;
          padding: 17px; font-size: 17px; outline: none; color: #071b3d; background: white;
        }
        input:focus, select:focus, textarea:focus {
          border-color: #1dcfc1; box-shadow: 0 0 0 4px rgba(29,207,193,.14);
        }
        textarea { min-height: 110px; resize: vertical; }
        .section { margin-top: 28px; }
        .chips { display: grid; grid-template-columns: repeat(2, 1fr); gap: 12px; }
        .chip {
          border: 2px solid #dfe9ea; background: white; color: #071b3d;
          border-radius: 20px; padding: 18px; font-size: 16px;
          font-weight: 900; text-align: left; cursor: pointer;
          transition: transform .18s ease, box-shadow .18s ease, background .18s ease;
        }
        .chip:hover { transform: translateY(-3px); box-shadow: 0 12px 28px rgba(7,27,61,.08); }
        .chip.active { border-color: #1dcfc1; background: #e9fbf9; }
        .chip.red.active { border-color: #d92d20; background: #fff1f1; color: #8a1f1f; }
        .button-row { display: flex; gap: 12px; flex-wrap: wrap; margin-top: 22px; }
        .button {
          border: none; background: #1dcfc1; color: white; border-radius: 18px;
          padding: 16px 24px; font-size: 17px; font-weight: 900;
          cursor: pointer; text-decoration: none; display: inline-flex;
          align-items: center; justify-content: center;
        }
        .button.secondary { background: #071b3d; }
        .button.danger { background: #d92d20; }
        .button.gold { background: #f79009; }
        .result { border-left: 9px solid #1dcfc1; }
        .result.emergency { border-left-color: #d92d20; }
        .result.doctor { border-left-color: #f79009; }
        .badge {
          display: inline-block; background: #eef8f8; color: #071b3d;
          padding: 10px 14px; border-radius: 999px; font-size: 12px;
          font-weight: 900; letter-spacing: .08em; text-transform: uppercase;
          margin-bottom: 18px;
        }
        .severity {
          display: inline-block; padding: 12px 16px; border-radius: 18px;
          font-weight: 900; margin-bottom: 16px;
        }
        .severity.emergency { background: #fff1f1; color: #b42318; }
        .severity.doctor { background: #fff7e6; color: #b54708; }
        .severity.pharmacist { background: #e9fbf9; color: #067367; }
        .result-line { font-size: 18px; color: #647480; line-height: 1.5; margin: 12px 0; }
        .result-line b { color: #071b3d; }
        .references {
          font-size: 14px; color: #6b7b86; line-height: 1.5;
          border-top: 1px solid #e4eeee; margin-top: 28px; padding-top: 18px;
        }
        @media (max-width: 700px) {
          .page { padding: 22px 14px 60px; }
          .brand-icon { width: 64px; height: 64px; font-size: 48px; }
          .brand-title { font-size: 42px; }
          .card { padding: 24px; border-radius: 28px; }
          .hero h1, .result h1 { font-size: 40px; }
          h2 { font-size: 28px; }
          .grid, .chips { grid-template-columns: 1fr; }
          .button { width: 100%; }
          p { font-size: 18px; }
        }
      `}</style>

      <main className="page">
        <div className="brand">
          <div className="brand-icon">+</div>
          <div>
            <div className="brand-title">SymptomAI</div>
            <div className="brand-subtitle">Right care. Right place. Right now.</div>
          </div>
        </div>

        {result ? (
          <section className={`card result ${result.routeType === 'emergency' ? 'emergency' : result.routeType === 'doctor' ? 'doctor' : ''}`}>
            <span className="badge">{result.level}</span>
            <div className={`severity ${result.routeType === 'emergency' ? 'emergency' : result.routeType === 'doctor' ? 'doctor' : 'pharmacist'}`}>
              {result.urgency}
            </div>
            <h1>{result.destination}</h1>

            <div className="result-line"><b>Advice:</b> {result.advice}</div>
            <div className="result-line"><b>Summary:</b> {result.summary}</div>
            <div className="result-line">
              <b>Clinical reference:</b> NICE CKS, South African STG/EML principles, pharmacist referral guidance and emergency escalation screening.
            </div>

            <div className="button-row">
              {result.routeType === 'emergency' && (
                <a className="button danger" href="tel:082911">Call Netcare 911</a>
              )}

              {result.routeType === 'doctor' && (
                <>
                  <a className="button" href={carelinkUrl} target="_blank">Book GP via Carelink</a>
                  <a className="button gold" href={pharmacistRouteUrl} target="_blank">Refer to Prescribing Pharmacist</a>
                </>
              )}

              <a className="button secondary" href={whatsappLink} target="_blank">WhatsApp report</a>
              <a className="button secondary" href={emailLink}>Email report</a>
              <button className="button secondary" onClick={downloadPDF}>Download PDF</button>
              <button className="button" onClick={newTriage}>New triage</button>
            </div>
          </section>
        ) : (
          <>
            <section className="card hero">
              <h1>60-second pharmacy triage</h1>
              <p>
                Capture symptoms, identify red flags, and route patients to emergency care,
                GP review, prescribing pharmacist care, or pharmacy-led self-care.
              </p>

              <div className="alert">Emergency in South Africa? Call Netcare 911: 082 911</div>

              <div className="button-row">
                <a className="button" href="#triage">Start triage</a>
                <button className="button secondary" onClick={installApp}>⬇ Install web app</button>
              </div>
            </section>

            <section className="card">
              <h2>Built for pharmacies</h2>
              <p>
                Interactive symptom selection, red-flag screening, clinical references,
                WhatsApp summaries, PDF reports, GP routing, and prescribing pharmacist referral.
              </p>
            </section>

            <section id="triage" className="card">
              <div className="chat">
                <strong>SymptomAI</strong>
                Let’s complete a quick pharmacy triage assessment.
              </div>

              <h2>Patient details</h2>

              <div className="grid">
                <div>
                  <label>Full name</label>
                  <input value={form.name} onChange={(e) => update('name', e.target.value)} placeholder="Patient name" />
                </div>

                <div>
                  <label>Age</label>
                  <input value={form.age} onChange={(e) => update('age', e.target.value)} placeholder="Age" />
                </div>

                <div>
                  <label>Country</label>
                  <select value={form.country} onChange={(e) => update('country', e.target.value)}>
                    <option value="South Africa">South Africa</option>
                    <option value="England">England</option>
                    <option value="Wales">Wales</option>
                    <option value="Scotland">Scotland</option>
                  </select>
                </div>

                <div>
                  <label>Gender</label>
                  <select value={form.gender} onChange={(e) => update('gender', e.target.value)}>
                    <option value="">Select gender</option>
                    <option value="male">Male</option>
                    <option value="female">Female</option>
                    <option value="other">Other / prefer not to say</option>
                  </select>
                </div>

                <div>
                  <label>Duration</label>
                  <select value={form.duration} onChange={(e) => update('duration', e.target.value)}>
                    <option value="">Select duration</option>
                    <option value="Less than 24 hours">Less than 24 hours</option>
                    <option value="Less than 3 days">Less than 3 days</option>
                    <option value="More than 3 days">More than 3 days</option>
                    <option value="Sudden or worsening">Sudden or worsening</option>
                  </select>
                </div>
              </div>

              {form.gender === 'female' && (
                <div className="section">
                  <label>Pregnant?</label>
                  <select value={form.pregnant} onChange={(e) => update('pregnant', e.target.value)}>
                    <option value="no">No</option>
                    <option value="yes">Yes</option>
                    <option value="unsure">Unsure</option>
                  </select>
                </div>
              )}

              <div className="section">
                <div className="chat">
                  <strong>SymptomAI</strong>
                  Select one or more symptoms from the alphabetical list.
                </div>

                <h2>Symptoms</h2>

                <div className="chips">
                  {symptoms.map((symptom) => (
                    <button
                      key={symptom}
                      className={`chip ${form.symptoms.includes(symptom) ? 'active' : ''}`}
                      onClick={() => toggleSymptom(symptom)}
                      type="button"
                    >
                      {form.symptoms.includes(symptom) ? '✓ ' : ''}
                      {symptom}
                    </button>
                  ))}
                </div>
              </div>

              <div className="section">
                <div className="chat">
                  <strong>SymptomAI</strong>
                  Check for red flags. If unsure, select it and refer upwards.
                </div>

                <h2>Red flags</h2>

                <div className="chips">
                  {redFlags.map((flag) => (
                    <button
                      key={flag}
                      className={`chip red ${form.redFlags.includes(flag) ? 'active' : ''}`}
                      onClick={() => toggleRedFlag(flag)}
                      type="button"
                    >
                      {form.redFlags.includes(flag) ? '✓ ' : ''}
                      {flag}
                    </button>
                  ))}
                </div>
              </div>

              <div className="section">
                <label>Pharmacist notes</label>
                <textarea value={form.notes} onChange={(e) => update('notes', e.target.value)} placeholder="Short pharmacist note" />
              </div>

              <button className="button" onClick={submitTriage}>Get triage recommendation</button>

              <div className="references">
                Clinical guidance references: NICE Clinical Knowledge Summaries, South African Primary Care/STG/EML principles, pharmacist referral guidance, WHO emergency escalation principles, and pharmacy minor ailment triage pathways.
              </div>
            </section>
          </>
        )}
      </main>
    </>
  );
}
